### ISSUE TITLE
Will the full crack be released?

### ISSUE THREAD

**Issue by xxgamerpro** [vk-nom/vape-v4-source#2]
Wondering if the full crack will be released because the kangaroo team is taking a long time.

**Comment by vk-nom** [comment]
im not sure, ill try to crack vape lite and manthe clicker but ive been pretty lazy recently so it might not happen.

**Comment by xxgamerpro** [comment]
Well V4 would be fine, thanks for the effort tho :)

**Comment by vk-nom** [comment]
v4 is already released....

**Comment by vk-nom** [comment]
look at the releases

**Comment by xxgamerpro** [comment]
I mean a full working vape crack.

**Comment by vk-nom** [comment]
this is a full working vape crack lmao

**Comment by xxgamerpro** [comment]
![image](https://user-images.githubusercontent.com/87397533/125873790-0eb8b1a7-d50c-445f-b978-a2b7f0a34ede.png)
???

**Comment by vk-nom** [comment]
hmmm works fine for me

**Comment by xxgamerpro** [comment]
Are you sure your not just logged into vape?

**Comment by Sasmisl** [comment]
> 
> 
> look at the releases

way what? where?
